modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"
#issueTrackerURL="https://github.com/..."

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''Far distance rendering mod utilising LoDs. Build ${commit} at ${buildtime}'''
displayTest="IGNORE_ALL_VERSION"
logoFile="assets/voxy/icon.png"
authors="Cortex"

[[mixins]]
config="client.voxy.mixins.json"
[[mixins]]
config="common.voxy.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.228,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[$minecraft]"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="sodium"
type="optional"
versionRange="[0.6.0,)"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="iris"
type="optional"
versionRange="[1.8,)"
ordering="NONE"
side="CLIENT"
